### ISSUE TITLE
Make it possible to automatically update bindings with this action

### ISSUE THREAD

**Issue by bbannier** [tree-sitter/parser-update-action#3]
Since recently tree-sitter-cli can generate e.g., Python bindings, however currently this action deliberately [does not update bindings](https://github.com/tree-sitter/parser-update-action/blob/master/action.yml#L34C1-L34C64). It would be great if this action provided at least an opt-in way to update these bindings as well. The tree-sitter CLI is already pretty careful to not mutilate existing configs, and having action support for this would make it much easier to e.g., automatically enable more bindings as upstream automation via `generate` for them becomes available.

**Comment by ObserverOfTime** [comment]
No. Updating bindings often requires manual intervention.
